//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace GoaSocietyRegistration.PayOnlineRef {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serviceSoap", Namespace="http://tempuri.org/")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback generateEchallanPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback generateEchallanPDFNewOperationCompleted;
        
        private System.Threading.SendOrPostCallback eChallanPaymentStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback eChallanSuccessPaymentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback eChallanPaymentDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback treasuryReceiptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback eChallanPaymentDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ereceiptOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGPFNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPpanNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateRefundOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::GoaSocietyRegistration.Properties.Settings.Default.GoaSocietyRegistration_PayOnlineRef_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event generateEchallanPDFCompletedEventHandler generateEchallanPDFCompleted;
        
        /// <remarks/>
        public event generateEchallanPDFNewCompletedEventHandler generateEchallanPDFNewCompleted;
        
        /// <remarks/>
        public event eChallanPaymentStatusCompletedEventHandler eChallanPaymentStatusCompleted;
        
        /// <remarks/>
        public event eChallanSuccessPaymentsCompletedEventHandler eChallanSuccessPaymentsCompleted;
        
        /// <remarks/>
        public event eChallanPaymentDataCompletedEventHandler eChallanPaymentDataCompleted;
        
        /// <remarks/>
        public event treasuryReceiptsCompletedEventHandler treasuryReceiptsCompleted;
        
        /// <remarks/>
        public event eChallanPaymentDetailsCompletedEventHandler eChallanPaymentDetailsCompleted;
        
        /// <remarks/>
        public event ereceiptCompletedEventHandler ereceiptCompleted;
        
        /// <remarks/>
        public event getGPFNameCompletedEventHandler getGPFNameCompleted;
        
        /// <remarks/>
        public event getPpanNameCompletedEventHandler getPpanNameCompleted;
        
        /// <remarks/>
        public event ValidateRefundCompletedEventHandler ValidateRefundCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/generateEchallanPDF", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet generateEchallanPDF(string demand, string encrypt_XML_data) {
            object[] results = this.Invoke("generateEchallanPDF", new object[] {
                        demand,
                        encrypt_XML_data});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void generateEchallanPDFAsync(string demand, string encrypt_XML_data) {
            this.generateEchallanPDFAsync(demand, encrypt_XML_data, null);
        }
        
        /// <remarks/>
        public void generateEchallanPDFAsync(string demand, string encrypt_XML_data, object userState) {
            if ((this.generateEchallanPDFOperationCompleted == null)) {
                this.generateEchallanPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateEchallanPDFOperationCompleted);
            }
            this.InvokeAsync("generateEchallanPDF", new object[] {
                        demand,
                        encrypt_XML_data}, this.generateEchallanPDFOperationCompleted, userState);
        }
        
        private void OngenerateEchallanPDFOperationCompleted(object arg) {
            if ((this.generateEchallanPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateEchallanPDFCompleted(this, new generateEchallanPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/generateEchallanPDFNew", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet generateEchallanPDFNew(string demand, string encrypt_XML_data, string serviceCode) {
            object[] results = this.Invoke("generateEchallanPDFNew", new object[] {
                        demand,
                        encrypt_XML_data,
                        serviceCode});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void generateEchallanPDFNewAsync(string demand, string encrypt_XML_data, string serviceCode) {
            this.generateEchallanPDFNewAsync(demand, encrypt_XML_data, serviceCode, null);
        }
        
        /// <remarks/>
        public void generateEchallanPDFNewAsync(string demand, string encrypt_XML_data, string serviceCode, object userState) {
            if ((this.generateEchallanPDFNewOperationCompleted == null)) {
                this.generateEchallanPDFNewOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateEchallanPDFNewOperationCompleted);
            }
            this.InvokeAsync("generateEchallanPDFNew", new object[] {
                        demand,
                        encrypt_XML_data,
                        serviceCode}, this.generateEchallanPDFNewOperationCompleted, userState);
        }
        
        private void OngenerateEchallanPDFNewOperationCompleted(object arg) {
            if ((this.generateEchallanPDFNewCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateEchallanPDFNewCompleted(this, new generateEchallanPDFNewCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eChallanPaymentStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eChallanPaymentStatus(string demandno, string encryptedEchallanno) {
            object[] results = this.Invoke("eChallanPaymentStatus", new object[] {
                        demandno,
                        encryptedEchallanno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eChallanPaymentStatusAsync(string demandno, string encryptedEchallanno) {
            this.eChallanPaymentStatusAsync(demandno, encryptedEchallanno, null);
        }
        
        /// <remarks/>
        public void eChallanPaymentStatusAsync(string demandno, string encryptedEchallanno, object userState) {
            if ((this.eChallanPaymentStatusOperationCompleted == null)) {
                this.eChallanPaymentStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OneChallanPaymentStatusOperationCompleted);
            }
            this.InvokeAsync("eChallanPaymentStatus", new object[] {
                        demandno,
                        encryptedEchallanno}, this.eChallanPaymentStatusOperationCompleted, userState);
        }
        
        private void OneChallanPaymentStatusOperationCompleted(object arg) {
            if ((this.eChallanPaymentStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eChallanPaymentStatusCompleted(this, new eChallanPaymentStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eChallanSuccessPayments", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eChallanSuccessPayments(string demandno, string encryptedXMLDates) {
            object[] results = this.Invoke("eChallanSuccessPayments", new object[] {
                        demandno,
                        encryptedXMLDates});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eChallanSuccessPaymentsAsync(string demandno, string encryptedXMLDates) {
            this.eChallanSuccessPaymentsAsync(demandno, encryptedXMLDates, null);
        }
        
        /// <remarks/>
        public void eChallanSuccessPaymentsAsync(string demandno, string encryptedXMLDates, object userState) {
            if ((this.eChallanSuccessPaymentsOperationCompleted == null)) {
                this.eChallanSuccessPaymentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OneChallanSuccessPaymentsOperationCompleted);
            }
            this.InvokeAsync("eChallanSuccessPayments", new object[] {
                        demandno,
                        encryptedXMLDates}, this.eChallanSuccessPaymentsOperationCompleted, userState);
        }
        
        private void OneChallanSuccessPaymentsOperationCompleted(object arg) {
            if ((this.eChallanSuccessPaymentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eChallanSuccessPaymentsCompleted(this, new eChallanSuccessPaymentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eChallanPaymentData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eChallanPaymentData(string demandno, string encryptedXMLDates) {
            object[] results = this.Invoke("eChallanPaymentData", new object[] {
                        demandno,
                        encryptedXMLDates});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eChallanPaymentDataAsync(string demandno, string encryptedXMLDates) {
            this.eChallanPaymentDataAsync(demandno, encryptedXMLDates, null);
        }
        
        /// <remarks/>
        public void eChallanPaymentDataAsync(string demandno, string encryptedXMLDates, object userState) {
            if ((this.eChallanPaymentDataOperationCompleted == null)) {
                this.eChallanPaymentDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OneChallanPaymentDataOperationCompleted);
            }
            this.InvokeAsync("eChallanPaymentData", new object[] {
                        demandno,
                        encryptedXMLDates}, this.eChallanPaymentDataOperationCompleted, userState);
        }
        
        private void OneChallanPaymentDataOperationCompleted(object arg) {
            if ((this.eChallanPaymentDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eChallanPaymentDataCompleted(this, new eChallanPaymentDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/treasuryReceipts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string treasuryReceipts(string demandno, string encryptedXMLDates) {
            object[] results = this.Invoke("treasuryReceipts", new object[] {
                        demandno,
                        encryptedXMLDates});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void treasuryReceiptsAsync(string demandno, string encryptedXMLDates) {
            this.treasuryReceiptsAsync(demandno, encryptedXMLDates, null);
        }
        
        /// <remarks/>
        public void treasuryReceiptsAsync(string demandno, string encryptedXMLDates, object userState) {
            if ((this.treasuryReceiptsOperationCompleted == null)) {
                this.treasuryReceiptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OntreasuryReceiptsOperationCompleted);
            }
            this.InvokeAsync("treasuryReceipts", new object[] {
                        demandno,
                        encryptedXMLDates}, this.treasuryReceiptsOperationCompleted, userState);
        }
        
        private void OntreasuryReceiptsOperationCompleted(object arg) {
            if ((this.treasuryReceiptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.treasuryReceiptsCompleted(this, new treasuryReceiptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/eChallanPaymentDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string eChallanPaymentDetails(string demandno, string encryptedEchallanno) {
            object[] results = this.Invoke("eChallanPaymentDetails", new object[] {
                        demandno,
                        encryptedEchallanno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eChallanPaymentDetailsAsync(string demandno, string encryptedEchallanno) {
            this.eChallanPaymentDetailsAsync(demandno, encryptedEchallanno, null);
        }
        
        /// <remarks/>
        public void eChallanPaymentDetailsAsync(string demandno, string encryptedEchallanno, object userState) {
            if ((this.eChallanPaymentDetailsOperationCompleted == null)) {
                this.eChallanPaymentDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OneChallanPaymentDetailsOperationCompleted);
            }
            this.InvokeAsync("eChallanPaymentDetails", new object[] {
                        demandno,
                        encryptedEchallanno}, this.eChallanPaymentDetailsOperationCompleted, userState);
        }
        
        private void OneChallanPaymentDetailsOperationCompleted(object arg) {
            if ((this.eChallanPaymentDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eChallanPaymentDetailsCompleted(this, new eChallanPaymentDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ereceipt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ereceipt(string demandno, string enc_echallanno) {
            object[] results = this.Invoke("ereceipt", new object[] {
                        demandno,
                        enc_echallanno});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ereceiptAsync(string demandno, string enc_echallanno) {
            this.ereceiptAsync(demandno, enc_echallanno, null);
        }
        
        /// <remarks/>
        public void ereceiptAsync(string demandno, string enc_echallanno, object userState) {
            if ((this.ereceiptOperationCompleted == null)) {
                this.ereceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnereceiptOperationCompleted);
            }
            this.InvokeAsync("ereceipt", new object[] {
                        demandno,
                        enc_echallanno}, this.ereceiptOperationCompleted, userState);
        }
        
        private void OnereceiptOperationCompleted(object arg) {
            if ((this.ereceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ereceiptCompleted(this, new ereceiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getGPFName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getGPFName(string encryptedGPFnoDetails) {
            object[] results = this.Invoke("getGPFName", new object[] {
                        encryptedGPFnoDetails});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGPFNameAsync(string encryptedGPFnoDetails) {
            this.getGPFNameAsync(encryptedGPFnoDetails, null);
        }
        
        /// <remarks/>
        public void getGPFNameAsync(string encryptedGPFnoDetails, object userState) {
            if ((this.getGPFNameOperationCompleted == null)) {
                this.getGPFNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGPFNameOperationCompleted);
            }
            this.InvokeAsync("getGPFName", new object[] {
                        encryptedGPFnoDetails}, this.getGPFNameOperationCompleted, userState);
        }
        
        private void OngetGPFNameOperationCompleted(object arg) {
            if ((this.getGPFNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGPFNameCompleted(this, new getGPFNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPpanName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getPpanName(string encryptedPpannoDetails) {
            object[] results = this.Invoke("getPpanName", new object[] {
                        encryptedPpannoDetails});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPpanNameAsync(string encryptedPpannoDetails) {
            this.getPpanNameAsync(encryptedPpannoDetails, null);
        }
        
        /// <remarks/>
        public void getPpanNameAsync(string encryptedPpannoDetails, object userState) {
            if ((this.getPpanNameOperationCompleted == null)) {
                this.getPpanNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPpanNameOperationCompleted);
            }
            this.InvokeAsync("getPpanName", new object[] {
                        encryptedPpannoDetails}, this.getPpanNameOperationCompleted, userState);
        }
        
        private void OngetPpanNameOperationCompleted(object arg) {
            if ((this.getPpanNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPpanNameCompleted(this, new getPpanNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateRefund", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateRefund(string encryptedRefundDetails) {
            object[] results = this.Invoke("ValidateRefund", new object[] {
                        encryptedRefundDetails});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateRefundAsync(string encryptedRefundDetails) {
            this.ValidateRefundAsync(encryptedRefundDetails, null);
        }
        
        /// <remarks/>
        public void ValidateRefundAsync(string encryptedRefundDetails, object userState) {
            if ((this.ValidateRefundOperationCompleted == null)) {
                this.ValidateRefundOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateRefundOperationCompleted);
            }
            this.InvokeAsync("ValidateRefund", new object[] {
                        encryptedRefundDetails}, this.ValidateRefundOperationCompleted, userState);
        }
        
        private void OnValidateRefundOperationCompleted(object arg) {
            if ((this.ValidateRefundCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateRefundCompleted(this, new ValidateRefundCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void generateEchallanPDFCompletedEventHandler(object sender, generateEchallanPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateEchallanPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateEchallanPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void generateEchallanPDFNewCompletedEventHandler(object sender, generateEchallanPDFNewCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateEchallanPDFNewCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateEchallanPDFNewCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eChallanPaymentStatusCompletedEventHandler(object sender, eChallanPaymentStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eChallanPaymentStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eChallanPaymentStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eChallanSuccessPaymentsCompletedEventHandler(object sender, eChallanSuccessPaymentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eChallanSuccessPaymentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eChallanSuccessPaymentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eChallanPaymentDataCompletedEventHandler(object sender, eChallanPaymentDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eChallanPaymentDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eChallanPaymentDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void treasuryReceiptsCompletedEventHandler(object sender, treasuryReceiptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class treasuryReceiptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal treasuryReceiptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void eChallanPaymentDetailsCompletedEventHandler(object sender, eChallanPaymentDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eChallanPaymentDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eChallanPaymentDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ereceiptCompletedEventHandler(object sender, ereceiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ereceiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ereceiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getGPFNameCompletedEventHandler(object sender, getGPFNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGPFNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGPFNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPpanNameCompletedEventHandler(object sender, getPpanNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPpanNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPpanNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateRefundCompletedEventHandler(object sender, ValidateRefundCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateRefundCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateRefundCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591